include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - initialize
  - publish

clean-install:
  stage: initialize
  image: node:18
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules
      - out

publish-cloudflare:
  stage: publish
  rules:
    - if: $CI_COMMIT_REF_PROTECTED && $CI_COMMIT_TAG =~ /^v/
  image: node:18
  dependencies: [initialize]
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
    - npm version $CI_COMMIT_TAG
    - npm publish
