on:
  push:
    tags:
      - v*

jobs:

  publish-cloudflare:
    runs-on: ubuntu-latest
    container: node:18
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID}}
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: >
          npx wrangler pages publish ./out
          --commit-dirty=true
          --project-name $(basename $GITHUB_REPOSITORY)
          --branch main
